name: XPBank
version: 1.5.3
main: net.killcraft.xpbank.XPBank
api-version: 1.21
author: lapure aka dwAsoR

commands:
  xpbank:
    description: Öffnet die XP-Bank GUI.
    permission: xpbank.use
    permission-message: §cDazu hast du keine Rechte! (Benötigt xpbank.use oder OP)
    
