name: XPBank
version: 1.2
main: net.killcraft.xpbank.XPBank
api-version: 1.21
author: KillCraft_Dev

commands:
  xpbank:
    description: Öffnet die XP-Bank GUI.
    permission: xpbank.use
    permission-message: §cDazu hast du keine Rechte! (Benötigt xpbank.use oder OP)
    
